/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as ApiFeedbackRouteImport } from './routes/api.feedback'
import { Route as ApiFxRateRouteImport } from './routes/api.fx-rate'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppReviewRouteImport } from './routes/app.review'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as ApiCronDailyCheckinRouteImport } from './routes/api.cron.daily-checkin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFxRateRoute = ApiFxRateRouteImport.update({
  id: '/api/fx-rate',
  path: '/api/fx-rate',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ApiCronDailyCheckinRoute = ApiCronDailyCheckinRouteImport.update({
  id: '/api/cron/daily-checkin',
  path: '/api/cron/daily-checkin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/preview': typeof PreviewRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/fx-rate': typeof ApiFxRateRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/cron/daily-checkin': typeof ApiCronDailyCheckinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preview': typeof PreviewRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/fx-rate': typeof ApiFxRateRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/api/cron/daily-checkin': typeof ApiCronDailyCheckinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/preview': typeof PreviewRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/fx-rate': typeof ApiFxRateRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/cron/daily-checkin': typeof ApiCronDailyCheckinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/preview'
    | '/api/feedback'
    | '/api/fx-rate'
    | '/app/insights'
    | '/app/review'
    | '/app/settings'
    | '/app/'
    | '/api/cron/daily-checkin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/preview'
    | '/api/feedback'
    | '/api/fx-rate'
    | '/app/insights'
    | '/app/review'
    | '/app/settings'
    | '/app'
    | '/api/cron/daily-checkin'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/preview'
    | '/api/feedback'
    | '/api/fx-rate'
    | '/app/insights'
    | '/app/review'
    | '/app/settings'
    | '/app/'
    | '/api/cron/daily-checkin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PreviewRoute: typeof PreviewRoute
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  ApiFxRateRoute: typeof ApiFxRateRoute
  ApiCronDailyCheckinRoute: typeof ApiCronDailyCheckinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fx-rate': {
      id: '/api/fx-rate'
      path: '/api/fx-rate'
      fullPath: '/api/fx-rate'
      preLoaderRoute: typeof ApiFxRateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review': {
      id: '/app/review'
      path: '/review'
      fullPath: '/app/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/cron/daily-checkin': {
      id: '/api/cron/daily-checkin'
      path: '/api/cron/daily-checkin'
      fullPath: '/api/cron/daily-checkin'
      preLoaderRoute: typeof ApiCronDailyCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppInsightsRoute: typeof AppInsightsRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInsightsRoute: AppInsightsRoute,
  AppReviewRoute: AppReviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PreviewRoute: PreviewRoute,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ApiFxRateRoute: ApiFxRateRoute,
  ApiCronDailyCheckinRoute: ApiCronDailyCheckinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
